[project]
name = "mcp-amadeus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "amadeus>=12.0.0",
    "mcp[cli]>=1.6.0",
]
